# Generated by Django 5.2.10 on 2026-01-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
